<?php
require_once __DIR__.'/../funciones.php'; requireRole('Guardia','..');
$id=(int)($_GET['id']??0);
$st=mysqli_prepare($conn,"SELECT v.*,vi.nombre_completo,vi.numero_identidad,vi.telefono,u.nombre_completo guardia,c.codigo codigo_autorizado FROM visitas v JOIN visitantes vi ON vi.id_visitante=v.id_visitante JOIN usuarios u ON u.id_usuario=v.id_usuario_registro JOIN codigos_qr c ON c.id_codigo_qr=v.id_codigo_qr WHERE v.id_visita=?");
mysqli_stmt_bind_param($st,'i',$id);mysqli_stmt_execute($st);$v=mysqli_fetch_assoc(mysqli_stmt_get_result($st));if(!$v)redirect('dashboard.php');
$titulo='Pase de visitante';$base='..';include __DIR__.'/../header.php'; ?>
<div class="page-head"><div><h1>Pase QR asignado</h1><p>Este QR está reservado para esta visita hasta que el vigilante marque “Ya salió”. Después volverá a estar disponible para otro visitante.</p></div><div><button class="btn secondary" onclick="window.print()">🖨️ Imprimir pase</button> <a class="btn ghost" href="dashboard.php">← Volver</a></div></div>
<div class="pass-card"><img class="pass-logo" src="../assets/logo.png" alt="Logo"><div class="pass-top"><span>PASE DE VISITANTE</span><strong><?=e(strtoupper($v['estado_visita']))?></strong></div><div id="qrcode" class="qr-box"><noscript><code><?=e($v['codigo_autorizado'])?></code></noscript></div><code class="qr-code"><?=e($v['codigo_autorizado'])?></code><div class="physical-code">QR reutilizable asignado: <strong><?=e($v['codigo_autorizado'])?></strong></div><div class="pass-data"><div><span>Visitante</span><b><?=e($v['nombre_completo'])?></b></div><div><span>DNI</span><b><?=e($v['numero_identidad'])?></b></div><div><span>Persona a visitar</span><b><?=e($v['persona_a_visitar'])?></b></div><div><span>Área</span><b><?=e($v['area_destino'])?></b></div><div class="full"><span>Motivo</span><b><?=e($v['motivo'])?></b></div></div></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script><script>const el=document.getElementById('qrcode');if(window.QRCode){new QRCode(el,{text:<?=json_encode($v['codigo_autorizado'])?>,width:220,height:220,correctLevel:QRCode.CorrectLevel.H});}else{el.innerHTML='<p>No se pudo dibujar el QR. Código: <strong><?=e($v['codigo_autorizado'])?></strong></p>';}</script>
<?php include __DIR__.'/../footer.php'; ?>
