<?php
require_once __DIR__.'/../funciones.php'; requireRole('Admin','..');
$tipo=($_GET['tipo']??'diario')==='general'?'general':'diario';$fecha=$_GET['fecha']??date('Y-m-d');
$baseSql="SELECT v.*,vi.nombre_completo,vi.numero_identidad,u.nombre_completo guardia FROM visitas v JOIN visitantes vi ON vi.id_visitante=v.id_visitante JOIN usuarios u ON u.id_usuario=v.id_usuario_registro";
if($tipo==='diario'){$st=mysqli_prepare($conn,$baseSql." WHERE DATE(v.fecha_registro)=? ORDER BY v.fecha_registro DESC");mysqli_stmt_bind_param($st,'s',$fecha);mysqli_stmt_execute($st);$lista=mysqli_stmt_get_result($st)->fetch_all(MYSQLI_ASSOC);}else{$lista=mysqli_query($conn,$baseSql." ORDER BY v.fecha_registro DESC")->fetch_all(MYSQLI_ASSOC);}
$activas=$finalizadas=$pendientes=$canceladas=0;foreach($lista as $v){$activas+=(int)($v['estado_visita']==='Activa');$finalizadas+=(int)($v['estado_visita']==='Finalizada');$pendientes+=(int)($v['estado_visita']==='Pendiente');$canceladas+=(int)($v['estado_visita']==='Cancelada');}
$titulo='Reportes';$base='..';include __DIR__.'/../header.php'; ?>
<div class="report-print-head"><img src="../assets/logo.png" alt="Logo"><div><h2>C.E.M.G. Técnico “Dr. Jorge Fidel Durón”</h2><p>Reporte de Control de Visitas</p></div></div>
<div class="page-head"><div><h1>Reportes administrativos</h1><p>Consulta diaria o general y utilice el botón de impresión.</p></div><div><button class="btn secondary" onclick="window.print()">🖨️ Imprimir</button> <a class="btn ghost" href="dashboard.php">← Volver</a></div></div>
<form class="searchbar no-print"><select name="tipo" id="tipoReporte" onchange="this.form.submit()"><option value="diario" <?=$tipo==='diario'?'selected':''?>>Reporte diario</option><option value="general" <?=$tipo==='general'?'selected':''?>>Reporte general (todo el historial)</option></select><?php if($tipo==='diario'):?><input type="date" name="fecha" value="<?=e($fecha)?>"><?php endif;?><button class="btn secondary">Consultar</button></form>
<div class="stats five"><div class="stat"><span>Total</span><strong><?=count($lista)?></strong></div><div class="stat"><span>Pendientes</span><strong><?=$pendientes?></strong></div><div class="stat"><span>Activas</span><strong><?=$activas?></strong></div><div class="stat"><span>Finalizadas</span><strong><?=$finalizadas?></strong></div><div class="stat"><span>Canceladas</span><strong><?=$canceladas?></strong></div></div>
<div class="table-card"><table><thead><tr><th>Fecha</th><th>DNI / Visitante</th><th>Destino</th><th>Guardia</th><th>QR</th><th>Entrada / Salida</th><th>Estado</th></tr></thead><tbody><?php foreach($lista as $v):?><tr><td><?=e($v['fecha_registro'])?></td><td><strong><?=e($v['nombre_completo'])?></strong><br><small><?=e($v['numero_identidad'])?></small></td><td><?=e($v['persona_a_visitar'])?><br><small><?=e($v['area_destino'])?></small></td><td><?=e($v['guardia'])?></td><td><code><?=e($v['codigo_qr'])?></code></td><td><small>Entrada: <?=e($v['hora_entrada']?:'—')?><br>Salida: <?=e($v['hora_salida']?:'—')?></small></td><td><span class="badge <?=estadoClase($v['estado_visita'])?>"><?=e($v['estado_visita'])?></span></td></tr><?php endforeach;?></tbody></table></div>
<?php include __DIR__.'/../footer.php'; ?>
