<?php
require_once __DIR__.'/../funciones.php'; requireRole('Admin','..');
if($_SERVER['REQUEST_METHOD']==='POST'){
    $accion=$_POST['accion']??'';$id=(int)($_POST['id']??0);
    if($accion==='cancelar'){
        mysqli_begin_transaction($conn);try{$st=mysqli_prepare($conn,"SELECT id_codigo_qr,estado_visita FROM visitas WHERE id_visita=? FOR UPDATE");mysqli_stmt_bind_param($st,'i',$id);mysqli_stmt_execute($st);$v=mysqli_fetch_assoc(mysqli_stmt_get_result($st));if(!$v)throw new Exception('Visita no encontrada.');if(!in_array($v['estado_visita'],['Pendiente','Activa'],true))throw new Exception('Esta visita ya no puede cancelarse.');$st=mysqli_prepare($conn,"UPDATE visitas SET estado_visita='Cancelada',hora_salida=IF(estado_visita='Activa',NOW(),hora_salida) WHERE id_visita=?");mysqli_stmt_bind_param($st,'i',$id);mysqli_stmt_execute($st);liberarQrDeVisita($conn,(int)$v['id_codigo_qr']);mysqli_commit($conn);flash('success','Visita cancelada y QR liberado.');}catch(Throwable $e){mysqli_rollback($conn);flash('danger',$e->getMessage());}redirect('visitas.php');
    }
    if($accion==='eliminar'){
        mysqli_begin_transaction($conn);try{$st=mysqli_prepare($conn,"SELECT id_codigo_qr,estado_visita FROM visitas WHERE id_visita=? FOR UPDATE");mysqli_stmt_bind_param($st,'i',$id);mysqli_stmt_execute($st);$v=mysqli_fetch_assoc(mysqli_stmt_get_result($st));if(!$v)throw new Exception('Visita no encontrada.');if(in_array($v['estado_visita'],['Pendiente','Activa'],true))liberarQrDeVisita($conn,(int)$v['id_codigo_qr']);$st=mysqli_prepare($conn,"DELETE FROM visitas WHERE id_visita=?");mysqli_stmt_bind_param($st,'i',$id);mysqli_stmt_execute($st);mysqli_commit($conn);flash('success','Visita eliminada.');}catch(Throwable $e){mysqli_rollback($conn);flash('danger',$e->getMessage());}redirect('visitas.php');
    }
}
$q=trim($_GET['q']??'');$sql="SELECT v.*,vi.nombre_completo,vi.numero_identidad,u.nombre_completo guardia FROM visitas v JOIN visitantes vi ON vi.id_visitante=v.id_visitante JOIN usuarios u ON u.id_usuario=v.id_usuario_registro";
if($q!==''){$like='%'.$q.'%';$st=mysqli_prepare($conn,$sql." WHERE vi.numero_identidad LIKE ? OR vi.nombre_completo LIKE ? OR v.codigo_qr LIKE ? ORDER BY v.fecha_registro DESC");mysqli_stmt_bind_param($st,'sss',$like,$like,$like);mysqli_stmt_execute($st);$lista=mysqli_stmt_get_result($st)->fetch_all(MYSQLI_ASSOC);}else{$lista=mysqli_query($conn,$sql." ORDER BY v.fecha_registro DESC")->fetch_all(MYSQLI_ASSOC);}
$titulo='Visitas';$base='..';include __DIR__.'/../header.php'; ?>
<div class="page-head"><div><h1>Administrar visitas</h1><p>Consultar, editar, cancelar y eliminar registros. Las visitas activas o pendientes liberan su QR al cancelarse o eliminarse.</p></div><a class="btn ghost" href="dashboard.php">← Volver</a></div>
<form class="searchbar"><input name="q" value="<?=e($q)?>" placeholder="DNI, visitante o QR"><button class="btn secondary">Buscar</button><?php if($q):?><a class="btn ghost" href="visitas.php">Limpiar</a><?php endif;?></form>
<div class="table-card"><table><thead><tr><th>Fecha</th><th>Visitante</th><th>Motivo / destino</th><th>QR</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($lista as $v):?><tr><td><?=e($v['fecha_registro'])?></td><td><strong><?=e($v['nombre_completo'])?></strong><br><small><?=e($v['numero_identidad'])?></small></td><td><?=e($v['motivo'])?><br><small><?=e($v['persona_a_visitar'])?> · <?=e($v['area_destino'])?></small></td><td><code><?=e($v['codigo_qr'])?></code></td><td><span class="badge <?=estadoClase($v['estado_visita'])?>"><?=e($v['estado_visita'])?></span></td><td><div class="row-actions"><a class="btn small secondary" href="visita_form.php?id=<?=$v['id_visita']?>">Editar</a><?php if(in_array($v['estado_visita'],['Pendiente','Activa'],true)):?><form method="post" onsubmit="return confirm('¿Cancelar esta visita y liberar el QR?');"><input type="hidden" name="accion" value="cancelar"><input type="hidden" name="id" value="<?=$v['id_visita']?>"><button class="btn small ghost">Cancelar</button></form><?php endif;?><form method="post" onsubmit="return confirm('¿Eliminar definitivamente esta visita?');"><input type="hidden" name="accion" value="eliminar"><input type="hidden" name="id" value="<?=$v['id_visita']?>"><button class="btn small danger">Eliminar</button></form></div></td></tr><?php endforeach;?></tbody></table></div>
<?php include __DIR__.'/../footer.php'; ?>
